[package]
name = "algorithms_impl"
version = "0.1.0"
edition = "2021"

[dependencies]
numpy = "0.22.1"
pyo3 = "0.22.0"
rand = "0.8.5"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "algorithms_impl"
crate-type = ["cdylib"]
